DROP DATABASE IF EXISTS GroupFinder;
CREATE DATABASE GroupFinder;
	
SET GLOBAL event_scheduler = ON;

CREATE EVENT expireuser
ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 MINUTE
DO
DELETE FROM GroupFinder 
WHERE TIMESTAMPDIFF(MINUTE, createdAt , NOW()) > 1
;